### PR TITLE
Allow for parsing of large XML files

### PR DESCRIPTION
**Pull request by tamcap**
Hi Nicholas,

I was wondering if you would be interested in this patch allowing easyrdf to handle large XML files. The solution implemented is based on PHP documentation suggestion.

### CODE REVIEW

**Comment by tamcap** [comment]
@njh hey, any interest in this (and next) PR?

**Comment by k00ni** [comment]
As far as I can tell, this PR is replaced by #352

CC @njh

**Comment by tamcap** [comment]
I am fine with it being replaced by #352.

**Comment by njh** [comment]
Ok, lets close this PR then.

Assuming we can actually get #352 to work!

**Pull request closed without merging**
