### PR TITLE
Added Dockerfile to enable easier local development

### PR DESCRIPTION
**Pull request by k00ni**
**Advantages:**
* no need to install any software on your machine, just start and log into the Docker container to run EasyRdf test suite etc.
* preinstalled tools like raptor2-utils or Fuseki server allow easier access and usage, because they are already setup for you
* use a custom PHP ini file to override PHP settings (helpful, if you want to check behavior under certain limitations)
  * Dockerfile is built upon php:7.3-~~apache~~ cli

Use the `make` command to start and run the container. It logs you in as the `easyrdf` user, not with root.

### CODE REVIEW

**Comment by njh** [comment]
I don't personally use Docker but I can see why this is useful to you/others.

**Comment by k00ni** [comment]
> I don't personally use Docker but I can see why this is useful to you/others.

Docker is great if you want a stable dev-environment. 

I was thinking about my additions here and might have a smaller and cleaner version. Let me think about it.

**Comment by njh** [comment]
Would using PHP CLI be suitable for development instead of installing Apache?

Other thing to note is that `docker` should probably be added to [.gitattributes](https://github.com/easyrdf/easyrdf/blob/master/.gitattributes), so that it isn't included in the packagist download.

**Comment by k00ni** [comment]
I used the PHP-CLI version of the container instead of Apache. Also added `docker` folder to `.gitattributes`.

**Review by njh — APPROVED** [review]

**Pull request merged**
