### PR TITLE
removed scripts/copyright_updater.php

### PR DESCRIPTION
**Pull request by k00ni**
It has no real value and scripts being empty would pollute the folder list.

Ref: #320

### CODE REVIEW

**Comment by njh** [comment]
What was the reason for removing this?

> "It has no real value"

I am not sure why you think it has no value?

> "being empty would pollute the folder list."

I am not sure what this means?

**Comment by k00ni** [comment]
As far as I understand copyright laws, there is no need to frequently update the year in the header. I thought at the beginning it is just for updating, but it also raises an error if no copyright header was found.

**Comment by njh** [comment]
Ah, ok. So can just leave an old year? or maybe remove the year completely?

**Comment by k00ni** [comment]
I would suggest we do it like the Symfony team, for instance:

https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/CacheWarmer/ProxyCacheWarmer.php

I saw this style in other projects too. Advantages:

* No year to update
* Clear and no need for maintenance

We could use something like:

```
/*
 * This file is part of the EasyRdf package.
 *
 * (c) Nicholas J Humfrey
 * (c) Respective Github contributors, see https://github.com/easyrdf/easyrdf/graphs/contributors
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```

I am not sure if php_codesniffer has that, but PHP CS Fixer has a rule to enforce a certain header for each PHP file. This way we wouldn't have to worry about that in the future.

**Comment by k00ni** [comment]
Hi @njh, could find some time to think about my last remarks?

**Comment by njh** [comment]
Would be good to keep it simple and have `(c) Nicholas J Humfrey`.
I don't think there should be a `(c) Respective Github contributors` line - while I don't want to ignore the important contributions that other people have made,  I am not sure if that line means much in copyright law. It seems simpler to have a single entity owning the copyright of the code.

I agree that it would be better having CodeSniffer or PHP CS Fixer enforce the boilerplate automatically without running a separate script.

**Comment by k00ni** [comment]
OK, I will close this in favor of a future PR which implements the behavior we talked about:

* short info header on each file references LICENSE.md
* 1 entity which owns the code

I am not sure when I implement that so further help is appreciated.

**Pull request closed without merging**
