### PR TITLE
Issue #390: Add return types to be compatible with php 8.1.

### PR DESCRIPTION
**Pull request by LOBsTerr**
I also noticed that some of the method don't have return statements for every case:
Container.php

1. current
2. offsetGet

If you want we can handle it in the separate ticket

### CODE REVIEW

**Comment by zozlak** [comment]
Adding return type hints isn't enough. You must also ensure methods return value which is in line with the declaration, e.g. `Collection::offsetSet()` is now declared `void` but it returns a value.

Btw those problems can be easily checked with a static code analyzer like phpstan:
```
composer require phpstan/phpstan
vendor/bin/phpstan analyze -l 2 lib
```

Btw it means a backward-incompatible change in the EasyRdf API and it might also require adjustments in the tests (e.g. if there is a test checking that `Collection::offsetSet()` returns a value, it has to be adjusted as well).

**Comment by LOBsTerr** [comment]
@zozlak Yes, Indeed! I also noticed it, but forgot to mention it in the comment above. I will check these cases

**Comment by zerocrates** [comment]
I wonder if you might just want to use the `ReturnTypeWillChange` annotation. That's "kicking the can down the road" to a certain extent, but it allows you to fix these warnings/notices without altering the API, which makes it more likely they'll be merged/released.

It should also be easier to do.

**Comment by k00ni** [comment]
Whats wrong with #384 from @alexpott who already did that?

**Comment by zerocrates** [comment]
Ah, whoops. I'd seen that one before, but when I looked recently I saw the relatively strong recent activity on these 2 and had forgotten about the older one.

I do think it's probably the right move, to do it that way, at least to start?

**Comment by claudiu-cristea** [comment]
@k00ni @LOBsTerr @njh I think we should consider #384 and close this.

**Comment by LOBsTerr** [comment]
Let's close in favor of https://github.com/easyrdf/easyrdf/pull/384

**Pull request closed without merging**
