### PR TITLE
increase timeout in lib/Http/Client to avoid failing tests because of connection refusal

### PR DESCRIPTION
**Pull request by k00ni**
Timeout increase from 10 to 30. I saw a decrease in failing tests. Nevertheless, it might be better to avoid real time HTTP calls during tests and switch to mocks.

Further information on this: https://github.com/sweetyrdf/easyrdf/issues/7

Original PR: https://github.com/sweetyrdf/easyrdf/pull/13/files

### CODE REVIEW

**Comment by k00ni** [comment]
It fails on PHP 7.4, but I don't think it is because of this change. Can someone restart the build please?

**Comment by njh** [comment]
I am a bit unsure about increasing the default timeout.
If the timeout was increased a production system and an external system started slowing down, it could result in building up a large number of blocked concurrent PHP processes.

Do you know which test was timing out/failing?
I think it would be worth either changing the example test, or increasing the timeout for just that test.

**Comment by k00ni** [comment]
This time outs came randomly. Here is an example from my fork:

https://travis-ci.com/github/sweetyrdf/easyrdf/jobs/357836242#L525

I'd rather mock the client before performing requests or is it intentional that real requests are made during the test suite?

> If the timeout was increased a production system and an external system started slowing down, it could result in building up a large number of blocked concurrent PHP processes.

Good point.

**Comment by njh** [comment]
I was aiming to make the main library test suite (`make test-lib`) mock all the HTTP calls and not have any calls to external systems/dependencies.

However the examples are deliberately not mocked, so it is possible to know if the examples still work.
If they don't work, then they don't serve as good examples anymore and need to be changed/fixed.
But it is possible that maybe we don't want to run them/break the build just because an example is (temporarily?) not working.

I also run the examples separately on my CI server:
https://ci.aelius.com/job/easyrdf-examples/

**Comment by k00ni** [comment]
When thinking about it, maybe its better to exclude examples from the tests overall. My intention was, that this way we can make sure they all work as expected. You mentioned your CI server. That's a good place for them to run. Is there a way to add some kind of a badge in the README, which shows if an example fails on your CI server?

**Comment by njh** [comment]
Yup, looks like I could install this plugin to create embeddable build status badge:
https://plugins.jenkins.io/embeddable-build-status/

Although the server is on my home internet connection, not ideal.
Maybe could run Jenkins somewhere else.

**Comment by k00ni** [comment]
OK @njh unless you have any objections, I would like to close this PR. Your point about ...

> If the timeout was increased a production system and an external system started slowing down, it could result in building up a large number of blocked concurrent PHP processes.

... was convincing.

**Pull request closed without merging**
