### PR TITLE
fixes "The Graph::properties() and Resource::properties() methods don't handle properties in unknown namespaces correctly"

### PR DESCRIPTION
**Pull request by k00ni**
These changes were contributed by @zozlak on my fork:https://github.com/sweetyrdf/easyrdf/pull/18

Quote from his pull request:

> The problem is caused by https://github.com/easyrdf/easyrdf/blob/master/lib/Graph.php#L1256-L1259 which silently skips all properties within namespaces unknown to EasyRdf\RdfNamespace.

### CODE REVIEW

**Comment by njh** [comment]
I can't decide if this is a bug or a breaking API change.

It might be that people are dependent on the old behaviour - wether it was intended or not :confusing

**Comment by zozlak** [comment]
@njh - have you seen the replication example in https://github.com/sweetyrdf/easyrdf/issues/17 ?

Without this fix `properties()` and `propertyUris()` return differend number of properties for a resource (if a resource contains properties in unknown namespaces).

If you are certain it's not a bug but a feature, please at least describe it in the documentation (as it makes `properties()` unsafe for traversing all resource properties).

**Comment by njh** [comment]
Yup, I had a read of https://github.com/sweetyrdf/easyrdf/issues/17 and the test in the PR.

My concern is that if you are expecting things back in the format, `foo:bar` and then get back a URI instead, that might not be what you were expecting and may not be any use. Particularly if it has been behaving that way for a long time.

I agree that if it is determined not to be a bug, then it needs documenting.

I guess it depends on what you are trying to do with the returned data. What is your use-case @zozlak?

**Comment by zozlak** [comment]
> if you are expecting things back in the format, foo:bar and then get back a URI instead

No, you won't. With the fix you will get a shorthand form with the prefix automatically generated by the `RdfNamespace` class.

And the use case is *traverse all properties of a resource without knowing what are property URIs/shorthand*. Something very common for someone who using the EasyRdf to validate data coming from an unknown source (like me).

**Comment by njh** [comment]
Ah, sorry! I forgot that `shorten($uri, true)` created new "blank" namespaces.
The is the problem with boolean parameters - it isn't clear without reading the docs what it actually does 😕 

```php
$short = RdfNamespace::shorten($property, true);
```

So when the unknown URI gets shortened, your code knows what to do with `ns0:property`?

I wonder if it would be better to do a non-breaking change and add a "include unknown namespaces" parameter to the `properties()` functions.

**Comment by zozlak** [comment]
> So when the unknown URI gets shortened, your code knows what to do with ns0:property?

* sometimes yes, e.g. when I'm only comparing for equality with another property
* sometimes no but I don't care because I'm only interested in the value
* sometimes no but at least I see the property is there and I have a chance to do something about it (e.g. call `RdfNamespace::expand()` and check if I can recognize to full URI)

Also personally I'm pretty sure backward (in)compatibility is not so important here. The EasyRdf 1.0.0 has been released after almost five years and is anyway backward incompatible with the previous stable release. People who are happily using 0.9.1 (most of them for many years) won't upgrade anyway and ones who upgrade will have to adapt their code anyway. Libraries API do change in every library, that's life. The question is rather:

* Does this change make sense?
* If so, how severe the change is (meaning to which release it belongs - with the major, middle or minor vesrion number changed)?
* If not (if you consider the current behaviour as a feature), it's also fine, just please extend the `property()` method documentation so it explicitly says *Properties in namespaces not registered in the RdfNamespace class are skipped. If you want to get all properties of a resource, use propertyUris() method instead`.

**Comment by k00ni** [comment]
This triggers an important point I was thinking about for a while: How stable is EasyRdf's API and what do people expect?

For me, its currently about preserving status quo, even if it means to keep "buggy" behavior. On the other hand invite contributions, if possible. At the time I merged this change in my fork it felt more like an addition rather than an API break.

As far as I can tell, its a change in behavior, which I personally like because its more logical and what I expect. But such changes require us to bump the major version (1.x => 2.x) if we want to follow semver (https://semver.org/). Maybe we can "collect" such changes in a 2.x branch? 

What do you think?

Ref:
* https://semver.org/#spec-item-8
* https://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release

**Comment by njh** [comment]
@k00ni for the long delay again. I have been finding hard to find time to work on personal projects.

It would be good try and follow semver and not break the API without bumping up the major version number.
It seems likely that there are lots of projects stuck on version 0.9.x and haven't upgraded to 1.x yet.

Before the 1.0.0, we did try keeping a 0.9.x branch and a separate 1.x.x branch but it just creates more work and end up just concentrating on one of them. There is bound to be lots of merging pain.

If we bump up to version 2.x, it probably isn't that big a deal for most people - although we need to be really clear about what has changed/broken.  Bumping up the major version number of API breaking changes seems to be very common/normal for node.js packages.

**Comment by k00ni** [comment]
I decided it changes behavior and would require us to increase the major version. For now, we wanna keep workload small and therefore won't maintain multiple major versions of the library. 

Nevertheless, further discussion about the underlying issue can be conducted in #349

**Pull request closed without merging**
