### PR TITLE
Exact path matching for get

### PR DESCRIPTION
**Pull request by tamcap**
While trying to parse a (potentially malformed) RDF-XML document, I ended up having resources with properties containing slashes in them (see the test case for a reproducible example).

The real life document in question is available here: https://github.com/CrossRef/open-funder-registry/blob/master/registry.rdf Please note you will need #291 to `load()` it.

For any `$property` containing slashes, I would have a problem:

While `$resource->has($property)` would return `true`, the `$resource->get($property)` would return `null` (despite the value being non-null). This patch seems to have fixed this issue.

Now, it's possible that those properties are accessible in some other fashion and this patch is unnecessary - please let me know.

### CODE REVIEW

**Comment by njh** [comment]
I have been thinking about this PR and I think I probably won't merge it. But it is bad that `$resource->has($property)` and `$resource->get($property)` behave differently.


The way I intended that you do this is either by putting `<` round the URI `>`:

```php
$result = $resource->get("<$property>");
```

This is mentioned at the end of this page:
http://www.easyrdf.org/docs/property-paths

Or alternatively by creating a resource for the property:

```php
$prop = $graph->resource($property);
$result = $resource->get($prop);
```

Does that make sense? Is it a reasonable approach?

**Comment by k00ni** [comment]
As far as I understood the changes of @tamcap: If nothing works it tries the exact path. Is using the exact path not a valid option here? For me its an additional which enables more results when having (malformed?) data.

**Comment by k00ni** [comment]
It seems be a stale PR therefore @osma and @zozlak, I would like to hear your opinion on this PR and @njh objection, so we can come to a decision.

**Comment by tamcap** [comment]
Hey, sorry for lack of feedback. Due to the lack of action earlier we had to use our own fork for production code. We actually have since deprecated the feature that initiated this PR in the first place, so my participation here is probably not super productive. I think it's an improvement, but I will be fine with your decision either way.

**Comment by k00ni** [comment]
@njh already outline that he won't merge it and provided an alternative solution: https://github.com/easyrdf/easyrdf/pull/292#issuecomment-647158554

Thank you for the effort @tamcap anyway!

**Pull request closed without merging**
