### PR TITLE
Issue #390: Fix 8.1 deprecation warnings.

### PR DESCRIPTION
**Pull request by LOBsTerr**

### CODE REVIEW

**Comment by njh** [comment]
Thank you very much for looking into fixing support for PHP 8.1

Unfortunately I cannot merge a PR where the automated tests are failing.

It might be easier to submit multiple smaller Pull Requests - maybe starting with one that just adds the missing return types?

**Comment by LOBsTerr** [comment]
ok, lets split them. I will prepare the first one

**Comment by LOBsTerr** [comment]
@njh  https://github.com/easyrdf/easyrdf/pull/398

**Comment by claudiu-cristea** [comment]
@njh @LOBsTerr why not closing this in favour of #384 which is older and seems more complete. We really need PHP 8.1 support

**Comment by k00ni** [comment]
> We really need PHP 8.1 support

If it is urgent, you might wanna use my fork https://github.com/sweetrdf/easyrdf in the meantime. It has PHP 8.1 support and other improvements.

**Comment by claudiu-cristea** [comment]
> > We really need PHP 8.1 support
> 
> If it is urgent, you might wanna use my fork [sweetrdf/easyrdf](https://github.com/sweetrdf/easyrdf) in the meantime. It has PHP 8.1 support and other improvements.

@k00ni I would love to but it seems to have too many changes since 1.1.1

**Comment by zozlak** [comment]
> @k00ni I would love to but it seems to have too many changes since 1.1.1

I would say you give it a chance. It doesn't seem @k00ni introduced any unnecessary backward-incompatible changes to the API. Some minor ones were for sure required for PHP 8.1 compatibility but first, I guess you don't depend on a `$numberOfRemovedValues = unset($graph->someProperty)` syntax (which has to be dropped for PHP 8.1 compatibility) and second, if you want PHP 8.1 compatibility, you must leave with it's much stricter object model anyway. Also, @k00ni's fork passes [phpstan](https://phpstan.org/) on level 4 which is quite impressive if you check how many issues the phpstan reports on the current EasyRdf code base (some of them being neglectable but some being clear bugs).

Looking at the (lack of) @njh activity here as well as in the #384 no one can give any estimate for the PHP 8.1 patches to be merged and the @njh is the only person with merge and release privileges here.

**Pull request closed without merging**
